# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: python.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='python.proto',
  package='python.proto',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0cpython.proto\x12\x0cpython.proto\"\xb0\x03\n\x05Snake\x12\x18\n\x10length_in_inches\x18\x01 \x01(\x02\x12\x1f\n\x17\x63ircumference_in_inches\x18\x02 \x01(\x02\x12(\n\x05\x63olor\x18\x03 \x01(\x0b\x32\x19.python.proto.Snake.Color\x12\x12\n\nhas_rattle\x18\x04 \x01(\x08\x12\x13\n\x0bvenom_index\x18\x05 \x01(\x05\x12\r\n\x05notes\x18\x06 \x01(\t\x12\x17\n\x0fscales_per_inch\x18\x07 \x01(\x05\x12,\n\x07species\x18\x08 \x01(\x0e\x32\x1b.python.proto.Snake.Species\x12\x32\n\x0bterritories\x18\t \x03(\x0e\x32\x1d.python.proto.Snake.Territory\x1a\x31\n\x05\x43olor\x12\x0b\n\x03red\x18\x01 \x02(\x05\x12\r\n\x05green\x18\x02 \x02(\x05\x12\x0c\n\x04\x62lue\x18\x03 \x02(\x05\"#\n\x07Species\x12\n\n\x06PYTHON\x10\x00\x12\x0c\n\x08GARDENER\x10\x01\"7\n\tTerritory\x12\x0f\n\x0bRAIN_FOREST\x10\x00\x12\r\n\tGRASSLAND\x10\x01\x12\n\n\x06GARDEN\x10\x02')
)



_SNAKE_SPECIES = _descriptor.EnumDescriptor(
  name='Species',
  full_name='python.proto.Snake.Species',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PYTHON', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GARDENER', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=371,
  serialized_end=406,
)
_sym_db.RegisterEnumDescriptor(_SNAKE_SPECIES)

_SNAKE_TERRITORY = _descriptor.EnumDescriptor(
  name='Territory',
  full_name='python.proto.Snake.Territory',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RAIN_FOREST', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GRASSLAND', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GARDEN', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=408,
  serialized_end=463,
)
_sym_db.RegisterEnumDescriptor(_SNAKE_TERRITORY)


_SNAKE_COLOR = _descriptor.Descriptor(
  name='Color',
  full_name='python.proto.Snake.Color',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='red', full_name='python.proto.Snake.Color.red', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='green', full_name='python.proto.Snake.Color.green', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='blue', full_name='python.proto.Snake.Color.blue', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=320,
  serialized_end=369,
)

_SNAKE = _descriptor.Descriptor(
  name='Snake',
  full_name='python.proto.Snake',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='length_in_inches', full_name='python.proto.Snake.length_in_inches', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='circumference_in_inches', full_name='python.proto.Snake.circumference_in_inches', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='color', full_name='python.proto.Snake.color', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='has_rattle', full_name='python.proto.Snake.has_rattle', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='venom_index', full_name='python.proto.Snake.venom_index', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='notes', full_name='python.proto.Snake.notes', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scales_per_inch', full_name='python.proto.Snake.scales_per_inch', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='species', full_name='python.proto.Snake.species', index=7,
      number=8, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='territories', full_name='python.proto.Snake.territories', index=8,
      number=9, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_SNAKE_COLOR, ],
  enum_types=[
    _SNAKE_SPECIES,
    _SNAKE_TERRITORY,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=463,
)

_SNAKE_COLOR.containing_type = _SNAKE
_SNAKE.fields_by_name['color'].message_type = _SNAKE_COLOR
_SNAKE.fields_by_name['species'].enum_type = _SNAKE_SPECIES
_SNAKE.fields_by_name['territories'].enum_type = _SNAKE_TERRITORY
_SNAKE_SPECIES.containing_type = _SNAKE
_SNAKE_TERRITORY.containing_type = _SNAKE
DESCRIPTOR.message_types_by_name['Snake'] = _SNAKE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Snake = _reflection.GeneratedProtocolMessageType('Snake', (_message.Message,), dict(

  Color = _reflection.GeneratedProtocolMessageType('Color', (_message.Message,), dict(
    DESCRIPTOR = _SNAKE_COLOR,
    __module__ = 'python_pb2'
    # @@protoc_insertion_point(class_scope:python.proto.Snake.Color)
    ))
  ,
  DESCRIPTOR = _SNAKE,
  __module__ = 'python_pb2'
  # @@protoc_insertion_point(class_scope:python.proto.Snake)
  ))
_sym_db.RegisterMessage(Snake)
_sym_db.RegisterMessage(Snake.Color)


# @@protoc_insertion_point(module_scope)
